version: '3'
services:
  web:
    build: .
    restart: unless-stopped
    depends_on:
        - db
    ports:
        - "8080:8080"
    environment: 
        - TRANSITCLOCK_PROPERTIES=config/transitclock.properties
        - AGENCYID=ro.stpt
        - AGENCYNAME=STPT
        - GTFS_URL=https://data.opentransport.ro/routing/gtfs/gtfs-timisoara.zip
        - GTFSRTVEHICLEPOSITIONS=https://api.opentransport.ro/realtime/vehicle-positions/tm
        - POSTGRES_PORT_5432_TCP_ADDR=db
        - POSTGRES_PORT_5432_TCP_PORT=5432
        - PGPASSWORD=transitclock
    volumes: 
        - ./runtime/logs:/usr/local/transitclock/logs/ 
        - ./runtime/ehcache:/usr/local/transitclock/cache/
  db:
    image: postgres:9.6.3
    restart: unless-stopped
    environment: 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: transitclock
        POSTGRES_HOST_AUTH_METHOD: trust
    