
#export TRANSITCLOCK_PGPASSWORD=$TRANSITCLOCK_PGPASSWRD
#export TRANSITCLOCK_DOCKER_INSTANCE_NAME=$TRANSITCLOCK_DOCKER_INSTANCE_NAME
#export TRANSITCLOCK_DATABASE_NAME=$TRANSITCLOCK_DATABASE_NAME
#export TRANSITCLOCK_DATABASE_USER=$TRANSITCLOCK_TRANSITCLOCK_DATABASE_USER
#export TRANSITCLOCK_WEB_PORT=$TRANSITCLOCK_WEB_PORT
#export TRANSITCLOCK_DATABASE_PORT=$TRANSITCLOCK_DATABASE_PORT
#export TRANSITCLOCK_QUEUE_NAME=$TRANSITCLOCK_QUEUE_NAME
#export TRANSITCLOCK_GTFS_URL=$TRANSITCLOCK_GTFS_URL

export TRANSITCLOCK_PGPASSWORD=newry
export TRANSITCLOCK_DATABASE_USER=greenore
export TRANSITCLOCK_DOCKER_INSTANCE_NAME=transitclock-core-rail
export TRANSITCLOCK_DATABASE_NAME=transitclock-database-rail
export TRANSITCLOCK_WEB_PORT=8011
export TRANSITCLOCK_DATABASE_PORT=5411
export TRANSITCLOCK_QUEUE_NAME=transitclock-queue-rail
export TRANSITCLOCK_GTFS_URL=https://transitfeeds.com/p/la-metro/677/latest/download

export TRANSITCLOCK_ACENCY_NAME=LAMETRORAIL
export TRANSITCLOCK_ACENCYID=1

docker stop $TRANSITCLOCK_DOCKER_INSTANCE_NAME
docker stop $TRANSITCLOCK_QUEUE_NAME
docker stop $TRANSITCLOCK_DATABASE_NAME

docker rm $TRANSITCLOCK_DOCKER_INSTANCE_NAME
docker rm $TRANSITCLOCK_QUEUE_NAME
docker rm $TRANSITCLOCK_DATABASE_NAME

docker run --name $TRANSITCLOCK_DATABASE_NAME -p $TRANSITCLOCK_DATABASE_PORT:5432 -e POSTGRES_USER=$TRANSITCLOCK_DATABASE_USER -e POSTGRES_PASSWORD=$TRANSITCLOCK_PGPASSWORD -d postgres:9.6.3

docker run --name $TRANSITCLOCK_QUEUE_NAME -d hornetq-server

docker run --rm --link $TRANSITCLOCK_DATABASE_NAME:postgres \
  -e PGPASSWORD=$TRANSITCLOCK_PGPASSWORD \
  -e DATABASE_USER=$TRANSITCLOCK_DATABASE_USER \
  -e AGENCYNAME=$TRANSITCLOCK_ACENCY_NAME \
  -e AGENCYID=$TRANSITCLOCK_ACENCYID \
  -v ~/logs/$TRANSITCLOCK_DOCKER_INSTANCE_NAME/:/usr/local/transitclock/logs/ transitclock-server check_db_up.sh

docker run --rm --link $TRANSITCLOCK_DATABASE_NAME:postgres \
  -e PGPASSWORD=$TRANSITCLOCK_PGPASSWORD \
  -e DATABASE_USER=$TRANSITCLOCK_DATABASE_USER \
  -e AGENCYNAME=$TRANSITCLOCK_ACENCY_NAME \
  -e AGENCYID=$TRANSITCLOCK_ACENCYID \
  -v ~/logs/$TRANSITCLOCK_DOCKER_INSTANCE_NAME/:/usr/local/transitclock/logs/ transitclock-server create_tables.sh

docker run --rm --link $TRANSITCLOCK_DATABASE_NAME:postgres \
  -e PGPASSWORD=$TRANSITCLOCK_PGPASSWORD \
  -e DATABASE_USER=$TRANSITCLOCK_DATABASE_USER \
  -e AGENCYNAME=$TRANSITCLOCK_ACENCY_NAME \
  -e AGENCYID=$TRANSITCLOCK_ACENCYID \
  -e GTFS_URL=$TRANSITCLOCK_GTFS_URL \
  -v ~/logs/$TRANSITCLOCK_DOCKER_INSTANCE_NAME/:/usr/local/transitclock/logs/ transitclock-server import_gtfs.sh

docker run --rm --link $TRANSITCLOCK_DATABASE_NAME:postgres \
  -e PGPASSWORD=$TRANSITCLOCK_PGPASSWORD \
  -e DATABASE_USER=$TRANSITCLOCK_DATABASE_USER \
  -e AGENCYNAME=$TRANSITCLOCK_ACENCY_NAME \
  -e AGENCYID=$TRANSITCLOCK_ACENCYID \
  -v ~/logs/$TRANSITCLOCK_DOCKER_INSTANCE_NAME/:/usr/local/transitclock/logs/ transitclock-server create_api_key.sh

docker run --rm --link $TRANSITCLOCK_DATABASE_NAME:postgres \
  -e PGPASSWORD=$TRANSITCLOCK_PGPASSWORD \
  -e DATABASE_USER=$TRANSITCLOCK_DATABASE_USER \
  -e AGENCYNAME=$TRANSITCLOCK_ACENCY_NAME \
  -e AGENCYID=$TRANSITCLOCK_ACENCYID \
  -v ~/logs/$TRANSITCLOCK_DOCKER_INSTANCE_NAME/:/usr/local/transitclock/logs/ transitclock-server create_webagency.sh

docker run --name $TRANSITCLOCK_DOCKER_INSTANCE_NAME --rm \
  --link $TRANSITCLOCK_DATABASE_NAME:postgres \
  --link $TRANSITCLOCK_QUEUE_NAME:hornetq \
  -e PGPASSWORD=$TRANSITCLOCK_PGPASSWORD \
  -e DATABASE_USER=$TRANSITCLOCK_DATABASE_USER \
  -e AGENCYNAME=$TRANSITCLOCK_ACENCY_NAME \
  -e AGENCYID=$TRANSITCLOCK_ACENCYID \
    -e GTFS_URL=$TRANSITCLOCK_GTFS_URL \
  -v ~/logs/$TRANSITCLOCK_DOCKER_INSTANCE_NAME/:/usr/local/transitclock/logs/ \
  -v ~/ehcache/$TRANSITCLOCK_DOCKER_INSTANCE_NAME/:/usr/local/transitclock/cache/ \
  -p $TRANSITCLOCK_WEB_PORT:8080 transitclock-server  start_transitclock.sh
